---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /tmp/k8s-pv-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  volumeName: local-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-pvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-pvc
  template:
    metadata:
      labels:
        app: data-exchange-pvc
    spec:
      containers:
        - name: busybox
          image: busybox:1.37
          command: ["/bin/sh", "-c"]
          args:
            - while true; do echo "$(date)" >> /data/output.txt; sleep 5; done
          volumeMounts:
            - name: pvc-vol
              mountPath: /data
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: pvc-vol
              mountPath: /data
      volumes:
        - name: pvc-vol
          persistentVolumeClaim:
            claimName: local-pvc

