---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-sc
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-sc
  hostPath:
    path: /tmp/k8s-sc-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-sc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-sc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-sc
  template:
    metadata:
      labels:
        app: data-exchange-sc
    spec:
      containers:
        - name: busybox
          image: busybox:1.37
          command: ["/bin/sh", "-c"]
          args:
            - while true; do echo "$(date)" >> /data/output.txt; sleep 5; done
          volumeMounts:
            - name: sc-vol
              mountPath: /data
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: sc-vol
              mountPath: /data
      volumes:
        - name: sc-vol
          persistentVolumeClaim:
            claimName: local-pvc-sc

